version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:Synesta17@db:5432/AvitoDb
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:6.2.6-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379

  db:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Synesta17
      - POSTGRES_DB=AvitoDb
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"



